SERVICE_NAME: istio-deployer
NAMESPACE: istio-system
IMAGE_REPOSITORY: ghcr.io/netcracker/
IMAGE_NAME: qubership-istio-deployer
SA_NAME: istio-deployer-sa

meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_ROUTER_MODE: "sni-dnat"
trafficManagement:
  enabled: true
pilot:
  CPU_REQUEST: 200m
  CPU_LIMIT: 400m
  MEMORY_REQUEST: "256Mi"
  MEMORY_LIMIT: "1Gi"

ztunnel:
  CPU_REQUEST: "100m"
  CPU_LIMIT: "400m"
  MEMORY_REQUEST: "128Mi"
  MEMORY_LIMIT: "512Mi"

cni:
  CPU_REQUEST: "100m"
  CPU_LIMIT: "400m"
  MEMORY_REQUEST: "128Mi"
  MEMORY_LIMIT: "512Mi"

qubership_istio_deployer_image:

