name: Istio Build Docker image

on:
  push:
    branches:
      - main

jobs:
  load-configuration:
    runs-on: ubuntu-latest
    outputs:
      istio-version: ${{ steps.load_component.outputs.istio-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load configuration
        run: | 
          istio-version=$(grep "ISTIO_VERSION" $GITHUB_WORKSPACE/.github/configuration.yml | awk -F': ' '{print $2}')
          echo "istio-version=${istio-version}" >> "$GITHUB_OUTPUT"     

  build-and-upload:
    runs-on: ubuntu-latest
    needs: [ load-configuration ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load istio-deployer image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
              ghcr.io/netcracker/istio-deployer:latest
          context: ./
          file: Dockerfile
          platforms: linux/amd64   
          build-args: ISTIO_VERSION=${{ needs.load_configuration.outputs.istio-version }}
