name: Build Artifacts
permissions:
  contents: read
  packages: write
  actions: read
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'

env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  GITHUB_GROUP: ${{ github.repository_owner }}

concurrency:
  # On main/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  load-configuration:
    runs-on: ubuntu-latest
    outputs:
      istio-version: ${{ steps.load_configuration.outputs.istio-version }}
      istio-minor-version: ${{ steps.load_configuration.outputs.istio-minor-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load configuration
        id: load_configuration
        run: |
          ISTIO_VERSION="$(grep "ISTIO_VERSION" $GITHUB_WORKSPACE/.github/configuration.yml | awk -F': ' '{print $2}')"
          ISTIO_MINOR_VERSION="$(echo "${ISTIO_VERSION%.*}")"
          echo istio-version=${ISTIO_VERSION}
          
          echo istio-version="${ISTIO_VERSION}" >> "$GITHUB_OUTPUT"  
          echo istio-minor-version="${ISTIO_MINOR_VERSION}" >> "$GITHUB_OUTPUT" 
 
          # Get images
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${ISTIO_VERSION} TARGET_ARCH=amd64 sh - 
          ln -sf $(pwd)/istio-*/bin/istioctl /usr/local/bin/istioctl 
          istioctl manifest generate --set profile=ambient | grep 'image: docker' > images.yaml

          awk '/image:/ { sub(/:/, ": "); split($0, parts, /[:/ ]+/); name = parts[length(parts)-1]; sub("-","_", name); init=$0; sub(/^[ \t]+/, "", init); print name "_" init }' images.yaml > images.yaml.tmp 
          cat images.yaml.tmp >> ./helm-templates/istio-deployer/images.yaml
          # Set version
          if echo ${TAG_NAME} | grep ref; then
            TAG_CLEANED=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')
          else
            TAG_CLEANED=${TAG_NAME}
          fi
          ISTIO_DEPLOYER_IMAGE="ghcr.io/${GITHUB_GROUP}/qubership-istio-deployer:${ISTIO_MINOR_VERSION}-${TAG_CLEANED}"
          sed -i "s#^[[:space:]]*qubership_istio_deployer_image.*#qubership_istio_deployer_image: ${ISTIO_DEPLOYER_IMAGE}#g" "./helm-templates/istio-deployer/values.yaml"

      - name: Upload changes
        uses: actions/upload-artifact@v4
        with:
          name: images_files
          path: |
            ./helm-templates/istio-deployer/values.yaml
            ./helm-templates/istio-deployer/images.yaml

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "actions"

          git add -u
          git commit -m 'updating values-images.yaml before release'

  multiplatform_build:
    needs: [ load-configuration ]
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-istio-transfer
            file: docker-transfer/Dockerfile
            context: ""
          - name: qubership-istio-deployer
            file: ./Dockerfile
            context: .
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Prepare Group
        run: echo "GITHUB_GROUP=${GITHUB_GROUP,,}" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
        with:
          component: |
            [{
              "name": "${{ matrix.component.name }}", 
              "file": "${{ matrix.component.file }}",
              "context": "${{ matrix.component.context }}"
            }]
          checkout: false    
          download-artifact: true
          download-artifact-name: images_files
          download-artifact-path: ./helm-templates/istio-deployer/
          download-artifact-merge-multiple: true  
          platforms: linux/amd64,linux/arm64
          tags: "${{ needs.load-configuration.outputs.istio-minor-version }}-${{ env.TAG_NAME }},${{ needs.load-configuration.outputs.istio-minor-version }}-latest"
          registry: ghcr.io
          dry-run: ${{ github.event.pull_request.user.login == 'dependabot[bot]' ||  github.event_name == 'push' }} 
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}